## NUMPY Array and basics

In [1]:
import numpy as np 

## Creating array from list

In [3]:
arr_1d=np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d=np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)


1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


## List vs numpy array

In [4]:
py_list=[1,2,3]
print("python list multiplication", py_list*2)

np_array=np.array([1,2,3])
print("python array multiplication", np_array*2)

python list multiplication [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]


## Creating array from scratch


In [6]:
zeros=np.zeros((3,4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
full=np.full((2,2),7)
print("full array: \n",full)

full array: 
 [[7 7]
 [7 7]]


In [8]:
random=np.random.random((2,3))
print("random array: \n",random)

random array: 
 [[0.76319784 0.63954144 0.24440366]
 [0.89269079 0.37169268 0.58822503]]


In [2]:
import numpy as np 
sequence=np.arange(0,10,2)
print("sequence array: \n",sequence)

sequence array: 
 [0 2 4 6 8]


In [4]:
tensor=np.array(
    [
        [[1,2],[3,4]],

        [[5,6],[7,8]]
    ]
)
print("Tensor: ",tensor)

Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties


In [5]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape", arr.shape)
print("Dimension",arr.ndim)
print("Size", arr.size)
print("Data Type", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
Data Type int64


## Array Reshaping

In [8]:
arr=np.arange(12)
print("original", arr)

reshaped=arr.reshape((3,4))
print("\n Reshaped array", reshaped)

flattened=reshaped.flatten()
print("\n flattened",flattened)

#ravel -> returns original instead of copy (like flatten)
raveled=reshaped.ravel()
print("\n raveled array",raveled)

transpose=reshaped.T
print("\n transposed array", transpose)




original [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
